TARGET = busywait
FINAL_TARGET = busywait.elf
OBJS = main.o

INCDIR = 
CFLAGS = -O2 -G0 -Wall
CXXFLAGS = $(CFLAGS)
ASFLAGS = $(CFLAGS)

LIBDIR =
LDFLAGS =

PS3SDK=$(PS3DEV)/ps3sdk
include $(PS3SDK)/build.mak
